title: "Antonio D'Alessandro"
description: "Academic research on statistics, causal inference, and data science"
url: "https://antoniod5836.github.io"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: ""
footer_text: ""

sass:
    style: compressed
    sass_dir: _sass

nav:
  - name: "About"
    link: "/"
  - name: "CV"
    link: "cv.pdf"
  - name: "Contact"
    link: "contact"
